/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as GoogleChar123Char125RouteImport } from './routes/google{$}'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRecorteIaRouteImport } from './routes/admin_.recorte-ia'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleChar123Char125Route = GoogleChar123Char125RouteImport.update({
  id: '/google{$}',
  path: '/google{$}',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecorteIaRoute = AdminRecorteIaRouteImport.update({
  id: '/admin_/recorte-ia',
  path: '/admin/recorte-ia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/google{$}': typeof GoogleChar123Char125Route
  '/simulador': typeof SimuladorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/recorte-ia': typeof AdminRecorteIaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/google{$}': typeof GoogleChar123Char125Route
  '/simulador': typeof SimuladorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/recorte-ia': typeof AdminRecorteIaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/google{$}': typeof GoogleChar123Char125Route
  '/simulador': typeof SimuladorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin_/recorte-ia': typeof AdminRecorteIaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/google{$}'
    | '/simulador'
    | '/sitemap.xml'
    | '/admin/recorte-ia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/google{$}'
    | '/simulador'
    | '/sitemap.xml'
    | '/admin/recorte-ia'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/google{$}'
    | '/simulador'
    | '/sitemap.xml'
    | '/admin_/recorte-ia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GoogleChar123Char125Route: typeof GoogleChar123Char125Route
  SimuladorRoute: typeof SimuladorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminRecorteIaRoute: typeof AdminRecorteIaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google{$}': {
      id: '/google{$}'
      path: '/google{$}'
      fullPath: '/google{$}'
      preLoaderRoute: typeof GoogleChar123Char125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/recorte-ia': {
      id: '/admin_/recorte-ia'
      path: '/admin/recorte-ia'
      fullPath: '/admin/recorte-ia'
      preLoaderRoute: typeof AdminRecorteIaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GoogleChar123Char125Route: GoogleChar123Char125Route,
  SimuladorRoute: SimuladorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminRecorteIaRoute: AdminRecorteIaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
